import { useEffect, useState } from 'react'
import { Link, Route, Routes, useNavigate, useParams } from 'react-router-dom'
import { api } from './services/api'
import ProblemCard from './components/ProblemCard'
import SubmissionForm from './components/SubmissionForm'
import FeedbackCard from './components/FeedbackCard'
import LoadingState from './components/LoadingState'
import ErrorState from './components/ErrorState'

function Shell({ children }) {
  return <div className="app-shell"><header className="site-header"><Link to="/" className="brand"><span className="brand-symbol">BL</span><span>Blueprint <i>Lab</i></span></Link><nav><Link to="/">Practice</Link><Link to="/history">Attempts</Link></nav><Link className="header-action" to="/">Start a design <span>↗</span></Link></header><main>{children}</main><footer><span>BLUEPRINT LAB / LLD PRACTICE</span><span>Structured reasoning over perfect answers.</span></footer></div>
}

function useLoad(loader, deps = []) { const [state, setState] = useState({ loading: true, data: null, error: '' }); useEffect(() => { let active = true; setState({ loading: true, data: null, error: '' }); loader().then((data) => active && setState({ loading: false, data, error: '' })).catch((error) => active && setState({ loading: false, data: null, error: error.message })); return () => { active = false } }, deps); return state }

function HomePage() { const { loading, data: problems, error } = useLoad(api.problems); if (loading) return <LoadingState label="Loading practice briefs" />; if (error) return <ErrorState message={error} />; return <><section className="hero"><div className="hero-copy"><span className="eyebrow">LOW-LEVEL DESIGN / PRACTICE STUDIO</span><h1>Build the model<br /><em>before the code.</em></h1><p>Practice the decisions that make software feel inevitable: boundaries, responsibilities, collaboration, and change.</p><div className="hero-actions"><a className="button button-dark" href="#problems">Explore problems <span>↓</span></a><Link className="quiet-link" to="/history">Review attempts <span>↗</span></Link></div></div><div className="hero-note"><span className="note-line" /><p>Three interview-shaped briefs.<br />One clear place to sharpen your reasoning.</p><strong>01—03</strong></div></section><section id="problems" className="section-block"><div className="section-heading"><div><span className="eyebrow">Choose a brief</span><h2>Problems worth thinking through.</h2></div><span className="section-count">{problems.length} available</span></div><div className="problem-grid">{problems.map((problem) => <ProblemCard key={problem.id} problem={problem} />)}</div></section><section className="method-strip"><span className="eyebrow">The loop</span><div className="method-steps"><span>01 / Understand</span><span>02 / Model</span><span>03 / Explain</span><span>04 / Improve</span></div></section></> }

function ProblemPage() { const { id } = useParams(); const navigate = useNavigate(); const { loading, data: problem, error } = useLoad(() => api.problem(id), [id]); const [starting, setStarting] = useState(false); if (loading) return <LoadingState label="Opening brief" />; if (error) return <ErrorState message={error} />; async function start() { setStarting(true); try { const attempt = await api.createAttempt(problem.id); navigate(`/practice/${attempt.id}`) } catch (e) { setStarting(false) } } return <section className="detail-page"><Link className="back-link" to="/">← All problems</Link><div className="detail-top"><div><span className="eyebrow">Problem brief / 0{problem.id}</span><h1>{problem.title}</h1><p className="detail-description">{problem.description}</p></div><div className="detail-badge"><span className={`difficulty ${problem.difficulty.toLowerCase()}`}>{problem.difficulty}</span><small>45—60 min practice</small></div></div><div className="detail-layout"><article className="brief-content"><section><span className="eyebrow">The scenario</span><p className="lead">{problem.problemStatement}</p></section><section><span className="eyebrow">Requirements</span><ul>{problem.requirements.map((requirement) => <li key={requirement}>{requirement}</li>)}</ul></section><section><span className="eyebrow">Context & constraints</span><p>{problem.constraints}</p></section></article><aside className="brief-aside"><span className="eyebrow">Think about</span><div className="tag-list">{problem.expectedAreas.map((area) => <span key={area}>{area}</span>)}</div><button className="button button-dark button-wide" onClick={start} disabled={starting}>{starting ? 'Creating attempt...' : 'Start this practice'} <span>↗</span></button><p className="aside-note">Your solution will be evaluated against a fixed rubric. There is no single correct design.</p></aside></div></section> }

function PracticePage() { const { id } = useParams(); const navigate = useNavigate(); const { loading, data: attempt, error } = useLoad(() => api.attempt(id), [id]); const [submitting, setSubmitting] = useState(false); if (loading) return <LoadingState label="Preparing your workspace" />; if (error) return <ErrorState message={error} />; async function submit(submission) { setSubmitting(true); try { await api.submit(id, submission); await api.evaluate(id); navigate(`/attempts/${id}/feedback`) } catch (e) { setSubmitting(false); alert(e.message) } } return <section className="practice-page"><div className="practice-context"><Link className="back-link" to={`/problems/${attempt.problem.id}`}>← Back to brief</Link><span className="eyebrow">Practice / {attempt.problem.title}</span><h1>Show your work.</h1><p>{attempt.problem.description}</p><div className="mini-brief"><span>Focus areas</span><p>{attempt.problem.expectedAreas.join(' · ')}</p></div></div><SubmissionForm onSubmit={submit} submitting={submitting} /></section> }

function FeedbackPage() { const { id } = useParams(); const navigate = useNavigate(); const { loading, data: attempt, error } = useLoad(() => api.attempt(id), [id]); const [retrying, setRetrying] = useState(false); if (loading) return <LoadingState label="Loading evaluation" />; if (error) return <ErrorState message={error} />; const evaluation = attempt.evaluation; async function retry() { setRetrying(true); try { await api.retry(id); navigate(`/attempts/${id}/feedback`); window.location.reload() } catch (e) { setRetrying(false); alert(e.message) } } if (!evaluation || evaluation.status === 'EVALUATING') return <section className="status-page"><span className="eyebrow">Evaluation / {attempt.problem.title}</span><div className="status-orbit"><div className="loader" /></div><h1>Your design is being read.</h1><p>We are looking for decisions, evidence, and opportunities to make the model more resilient.</p></section>; if (evaluation.status === 'FAILED') return <section className="status-page failed"><span className="eyebrow">Evaluation paused</span><h1>Your submission is safe.</h1><p>{evaluation.errorMessage}</p><button className="button button-dark" onClick={retry} disabled={retrying}>{retrying ? 'Retrying...' : 'Retry evaluation'} <span>↗</span></button></section>; return <section className="feedback-page"><div className="feedback-hero"><div><span className="eyebrow">Completed / {attempt.problem.title}</span><h1>A useful first<br /><em>draft to build on.</em></h1><p>{evaluation.overallSummary}</p></div><div className="feedback-score"><span>Rubric signals</span><strong>{Math.round(evaluation.feedbackItems.reduce((sum, item) => sum + item.score, 0) / evaluation.feedbackItems.length * 20)}<small>/100</small></strong><small>Use the notes below, not the number, as your guide.</small></div></div><div className="feedback-columns"><section><div className="feedback-section-heading"><span className="eyebrow">Criterion feedback</span><h2>Where the design speaks.</h2></div>{evaluation.feedbackItems.map((item) => <FeedbackCard key={item.criterion} item={item} />)}</section><aside className="feedback-summary"><div><span className="eyebrow">Strengths</span><ul>{evaluation.strengths.map((item) => <li key={item}>{item}</li>)}</ul></div><div><span className="eyebrow">Improve next</span><ul className="improvements">{evaluation.improvementAreas.map((item) => <li key={item}>{item}</li>)}</ul></div><div><span className="eyebrow">Next steps</span><ol>{evaluation.nextSteps.map((item) => <li key={item}>{item}</li>)}</ol></div><button className="button button-dark button-wide" onClick={retry} disabled={retrying}>{retrying ? 'Creating retry...' : 'Try this problem again'} <span>↗</span></button><button className="text-button" onClick={() => navigate('/history')}>View attempt history →</button></aside></div></section> }

function HistoryPage() { const { loading, data: attempts, error } = useLoad(api.attempts); if (loading) return <LoadingState label="Loading your attempts" />; if (error) return <ErrorState message={error} />; return <section className="history-page"><div className="section-heading"><div><span className="eyebrow">Your notebook</span><h1>Attempts, in progress.</h1><p>Each pass is evidence of how your model is changing.</p></div><Link className="button button-dark" to="/">Choose a problem <span>↗</span></Link></div>{attempts.length ? <div className="attempt-list">{attempts.slice().reverse().map((attempt) => <article className="attempt-row" key={attempt.id}><div className="attempt-number">#{String(attempt.id).padStart(2, '0')}</div><div><span className="eyebrow">{attempt.problem.title}</span><h3>{new Date(attempt.createdAt).toLocaleDateString(undefined, { month: 'short', day: 'numeric', year: 'numeric' })}</h3></div><span className={`status status-${attempt.status.toLowerCase()}`}>{attempt.status.replace('_', ' ')}</span><div className="attempt-action">{attempt.status === 'COMPLETED' || attempt.status === 'FAILED' ? <Link to={`/attempts/${attempt.id}/feedback`}>Review <span>↗</span></Link> : <Link to={`/practice/${attempt.id}`}>Continue <span>↗</span></Link>}</div></article>)}</div> : <div className="empty-state"><span className="eyebrow">Nothing here yet</span><h2>Your first model is waiting.</h2><Link className="button button-dark" to="/">Browse problems <span>↗</span></Link></div>}</section> }

export default function App() { return <Shell><Routes><Route path="/" element={<HomePage />} /><Route path="/problems/:id" element={<ProblemPage />} /><Route path="/practice/:id" element={<PracticePage />} /><Route path="/attempts/:id/feedback" element={<FeedbackPage />} /><Route path="/history" element={<HistoryPage />} /></Routes></Shell> }
